name: Bump firmware

on:
    push:
        branches:
            - main

jobs:
    dispatch:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout smart-led-web-gui
              uses: actions/checkout@v4
              with:
                  repository: kd3n1z/smart-led-web-gui
                  path: ./smart-led-web-gui
            - name: Checkout smart-led-firmware
              uses: actions/checkout@v4
              with:
                  repository: kd3n1z/smart-led-firmware
                  path: ./smart-led-firmware
                  token: ${{ secrets.PAT }}
            - name: Setup Node
              uses: actions/setup-node@v4
            - name: Install dependencies
              working-directory: ./smart-led-web-gui
              run: npm ci
            - name: Build
              working-directory: ./smart-led-web-gui
              run: make prepare-firmware
            - name: Get version
              working-directory: ./smart-led-web-gui
              run: |
                  echo "COMMIT_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
                  echo "COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  repository: ./smart-led-firmware
                  commit_message: 'feat(frontend): update to commit ${{ env.COMMIT_SHORT }}


                      bumped frontend to commit https://github.com/kd3n1z/smart-led-web-gui/commit/${{ env.COMMIT }}'
                  commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
